import {  Poppins } from "next/font/google";
import "./globals.css";


const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  weight: ['400','500','600', '700'],  
  subsets: ['latin'],  
});



export const metadata = {
  title: "JF Shop | Home",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body
        className={`${poppinsSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
